// AUTO-GENERATED by scripts/gen-sdk-typings.mjs (npm run gen-typings) from src/apps/AppContext.js.
// Structural inference only (AppContext.js has no formal @param/@returns JSDoc blocks yet, so
// parameter/return types are mostly 'any') -- NOT a drop-in replacement for the hand-curated
// client/editor/sdk-typings.d.ts Monaco typings. Regenerate: npm run gen-typings.
// DO NOT EDIT BY HAND.

import { CliDebugger } from '../debug/CliDebugger.js';
export declare class AppContext {
    _entity: any;
    _runtime: any;
    _state: any;
    _entityProxy: {
        readonly id: any;
        readonly model: any;
        readonly bodyType: any;
        position: any;
        rotation: any;
        scale: any;
        velocity: any;
        custom: any;
        readonly parent: any;
        readonly children: any[];
        readonly worldTransform: any;
        destroy: () => any;
    };
    _debugger: CliDebugger;
    _busScope: any;
    _disposed: boolean;
    _pendingShutdownHooks: Set<any> | null;
    _physicsAPI: {
        setInteractable: (radius?: number) => void;
        setStatic: (v: any) => void;
        setDynamic: (v: any) => void;
        setKinematic: (v: any) => void;
        setMass: (v: any) => void;
        setLinearDamping: (v: any) => void;
        setAngularDamping: (v: any) => void;
        setCCDPolicy: (v: any) => void;
        addBoxCollider: (s: any, shapeKey: any) => void;
        addSphereCollider: (r: any) => void;
        addCapsuleCollider: (r: any, h: any) => void;
        addTrimeshCollider: () => Promise<void>;
        addConvexCollider: (points: any) => void;
        addConvexFromModel: (meshIndex?: number) => void;
        addConvexFromModelAsync: (meshIndex: number | undefined, shapeKeyOverride: any) => Promise<void>;
        addColliderFromConfig: (cfg?: {}) => Promise<void> | undefined;
        addForce: (f: any) => void;
        setVelocity: (v: any) => void;
        setPosition: (p: any) => void;
        getVelocity: () => any;
        getAngularVelocity: () => any;
        getRotation: () => any;
        isAtRest: (eps?: number) => boolean;
        tiltFromUpright: () => number;
        setFriction: (f: any) => boolean;
        setRestitution: (r: any) => boolean;
        setMotionType: (motionType: any) => any;
        getMotionType: () => any;
        getBodyId: () => any;
        createVehicle: (wheelDefs: any, opts: any) => any;
        setVehicleInput: (forward: any, right: any, brake: any, handbrake: any) => any;
        createTrackedVehicle: (wheelDefs: any, opts: any) => any;
        setTrackedVehicleInput: (forward: any, leftRatio: any, rightRatio: any, brake: any) => any;
        getVehicleWheelTransform: (wheelIndex: any) => any;
        getVehicleWheelState: (wheelIndex: any) => any;
        hasVehicle: () => boolean;
        destroyVehicle: () => any;
    } | undefined;
    _configListeners: Set<any> | null | undefined;
    _stores: Map<any, any> | undefined;
    _disposers: any[] | null | undefined;
    _chartAwareApis: any[] | undefined;
    _chartAwareWeak: any[] | undefined;
    constructor(entity: any, runtime: any);
    _admitsRegistration(kind: any): boolean;
    _buildEntityProxy(): {
        readonly id: any;
        readonly model: any;
        readonly bodyType: any;
        position: any;
        rotation: any;
        scale: any;
        velocity: any;
        custom: any;
        readonly parent: any;
        readonly children: any[];
        readonly worldTransform: any;
        destroy: () => any;
    };
    get entity(): {
        readonly id: any;
        readonly model: any;
        readonly bodyType: any;
        position: any;
        rotation: any;
        scale: any;
        velocity: any;
        custom: any;
        readonly parent: any;
        readonly children: any[];
        readonly worldTransform: any;
        destroy: () => any;
    };
    get physics(): {
        setInteractable: (radius?: number) => void;
        setStatic: (v: any) => void;
        setDynamic: (v: any) => void;
        setKinematic: (v: any) => void;
        setMass: (v: any) => void;
        setLinearDamping: (v: any) => void;
        setAngularDamping: (v: any) => void;
        setCCDPolicy: (v: any) => void;
        addBoxCollider: (s: any, shapeKey: any) => void;
        addSphereCollider: (r: any) => void;
        addCapsuleCollider: (r: any, h: any) => void;
        addTrimeshCollider: () => Promise<void>;
        addConvexCollider: (points: any) => void;
        addConvexFromModel: (meshIndex?: number) => void;
        addConvexFromModelAsync: (meshIndex: number | undefined, shapeKeyOverride: any) => Promise<void>;
        addColliderFromConfig: (cfg?: {}) => Promise<void> | undefined;
        addForce: (f: any) => void;
        setVelocity: (v: any) => void;
        setPosition: (p: any) => void;
        getVelocity: () => any;
        getAngularVelocity: () => any;
        getRotation: () => any;
        isAtRest: (eps?: number) => boolean;
        tiltFromUpright: () => number;
        setFriction: (f: any) => boolean;
        setRestitution: (r: any) => boolean;
        setMotionType: (motionType: any) => any;
        getMotionType: () => any;
        getBodyId: () => any;
        createVehicle: (wheelDefs: any, opts: any) => any;
        setVehicleInput: (forward: any, right: any, brake: any, handbrake: any) => any;
        createTrackedVehicle: (wheelDefs: any, opts: any) => any;
        setTrackedVehicleInput: (forward: any, leftRatio: any, rightRatio: any, brake: any) => any;
        getVehicleWheelTransform: (wheelIndex: any) => any;
        getVehicleWheelState: (wheelIndex: any) => any;
        hasVehicle: () => boolean;
        destroyVehicle: () => any;
    };
    get world(): {
        spawn: (id: any, cfg: any) => any;
        spawnChild: (id: any, cfg: any) => any;
        destroy: (id: any) => void;
        attach: (eid: any, app: any) => any;
        detach: (eid: any) => any;
        reparent: (eid: any, parentId: any) => any;
        query: (filter: any) => any;
        getEntity: (id: any) => any;
        nearby: (pos: any, radius: any) => any;
        sendToEntity: (entityId: any, msg: any) => any;
        applyImpulse: (entityId: any, impulse: any, worldPoint: any) => any;
        setVelocity: (entityId: any, velocity: any) => any;
        setGravityFactor: (entityId: any, factor: any) => any;
        setBodyActive: (entityId: any, active: any) => any;
        setPosition: (entityId: any, position: any, rotation: any) => any;
        weld: (entityA: any, entityB: any, opts: any) => any;
        joint: (entityA: any, entityB: any, opts: any) => any;
        removeConstraint: (constraintId: any) => any;
        setMotionType: (entityId: any, motionType: any) => any;
        isAtRest: (entityId: any, eps: any) => any;
        readonly gravity: any;
    };
    get players(): {
        getAll: () => any;
        getById: (id: any) => any;
        getNearest: (pos: any, r: any) => any;
        send: (pid: any, msg: any) => any;
        broadcast: (msg: any) => any;
        broadcastNearby: (pos: any, radius: any, msg: any) => void;
        setPosition: (pid: any, pos: any) => any;
        setName: (pid: any, name: any) => any;
        setAppearance: (pid: any, appearance: any) => any;
        setModel: (pid: any, url: any) => any;
        setWeapon: (pid: any, name: any) => any;
        setMovementOverride: (pid: any, overrides: any) => any;
        setLifecycle: (pid: any, state: any, opts: any) => any;
        playAnimation: (pid: any, clip: any, opts: any) => any;
        attachEntity: (pid: any, entityId: any, offset: any) => any;
        detachEntity: (entityId: any) => any;
        onPlayerContact: (radius: any, cb: any) => () => void;
        nearestOtherPlayer: (playerId: any, radius: any) => any;
    };
    get time(): {
        readonly tick: any;
        readonly deltaTime: any;
        readonly elapsed: any;
        readonly serverTime: number;
        after: (seconds: any, fn: any) => void;
        every: (seconds: any, fn: any) => void;
    };
    get config(): any;
    onConfigChange(cb: any): () => void;
    _fireConfigChange(): void;
    onShutdown(cb: any): () => void;
    get state(): any;
    set state(v: any);
    get network(): {
        broadcast: (msg: any) => any;
        sendTo: (id: any, msg: any) => any;
    };
    get lagCompensator(): any;
    get combat(): Readonly<{
        DEFAULT_HITBOX: Readonly<{
            centerHeight: 0.9;
            radiusSq: 0.36;
            height: 1.8;
        }>;
        normalizeShotDirection(d: any): number[] | null;
        resolveFireRequest(lagComp: any, shooterId: any, shooterPosition: any, msg: any, hitbox?: Readonly<{
            centerHeight: 0.9;
            radiusSq: 0.36;
            height: 1.8;
        }>): {
            origin: any;
            viewTick: any;
        };
        resolveTargetPoint(target: any, lagComp: any, viewTick: any): {
            tp: any;
            rewound: any;
        };
        rayVsCapsule(origin: any, direction: any, range: any, tp: any, hitbox?: Readonly<{
            centerHeight: 0.9;
            radiusSq: 0.36;
            height: 1.8;
        }>): {
            proj: any[];
            dot: number;
        } | null;
        hitHeightRatio(proj: any, tp: any, hitbox?: Readonly<{
            centerHeight: 0.9;
            radiusSq: 0.36;
            height: 1.8;
        }>): number;
        findHitLinear(players: any, shot: any): {
            target: any;
            tp: any;
            rewound: any;
            proj: any[];
            dot: number;
        } | null;
        findHitSpatial(players: any, shot: any, liveIndex?: null): null;
        buildLiveIndex: typeof import("../netcode/RewindSpatialIndex.js").buildLiveIndex;
        recordHit: typeof import("../netcode/OutlierDetector.js").recordHit;
    }>;
    fallFloorY(x: any, z: any, depth: any): number;
    pickSpawnPoint(spawnPoints: any, opts: any): any[];
    persisted(key: any, initial: any, opts: any): any;
    leaderboard(key: any, opts: any): any;
    _store(id: any, create: any): any;
    get bus(): any;
    get eventLog(): any;
    get storage(): {
        get: (key: any) => any;
        set: (key: any, value: any) => any;
        delete: (key: any) => any;
        list: (prefix?: string) => any;
        has: (key: any) => any;
    } | null;
    get debug(): CliDebugger;
    interactable(config?: {}): void;
    onPlayerProximity(radius: any, callback: any): () => void;
    _registerDisposer(fn: any): void;
    _runDisposers(): void;
    _chartAware(api: any): any;
    _chartAwareWeakly(api: any): any;
    _liveChartAwareApis(): any[];
    _blockChartReanchor(reason: any): () => void;
    _teardownChildren(): void;
    defineGameFSM(spec: any): {
        readonly context: any;
        readonly state: any;
        readonly timeInState: number;
        is(s: any): any;
        matches(s: any): any;
        can(evt: any): any;
        send(type: any, payload: any): void;
        onTransition(fn: any): () => void;
        tick(dt: any): void;
        stop(): void;
    };
    defineGameMode(spec: any): any;
    defineBuffStack(spec: any): {
        apply(playerId: any, buffKey: any, delta: any): any;
        set(playerId: any, buffKey: any, value: any): any;
        get(playerId: any, buffKey: any): any;
        getAll(playerId: any): {
            [k: string]: any;
        };
        clear(playerId: any, buffKey: any): void;
        clearAll(): void;
        tick(dt: any): void;
    };
    defineShrinkingZone(spec: any): any;
    defineHealth(spec: any): {
        readonly hp: any;
        readonly max: any;
        readonly alive: boolean;
        readonly fraction: number;
        damage(amount: any, source?: null): any;
        heal(amount: any): any;
        kill(source?: null): void;
        respawn(hp: any): any;
        setMax(m: any): any;
    };
    defineCombat(spec?: {}): any;
    defineFire(spec?: {}): {
        readonly world: any;
        readonly activeCount: any;
        readonly stats: any;
        readonly rollbackStats: {
            rewinds: number;
            resimTicks: number;
            droppedRows: number;
        };
        readonly resyncStats: {
            rows: number;
            compared: number;
            missed: number;
            mismatches: number;
            firstMismatch: null;
            requestsReceived: number;
            requestsSent: number;
            adopted: number;
        };
        readonly needsResync: boolean;
        readonly checksumHistory: [any, any][];
        readonly simTick: any;
        readonly names: string[];
        readonly weather: {
            step(simTick: any, out: any): any;
            readonly rain: number;
            readonly moisture: number;
            readonly emittedRain: number;
            readonly emittedMoisture: number;
            markEmitted(r: any, m: any): void;
        } | null;
        readonly gameplay: {
            tickDamage: (simTick: any, dt: any) => void;
            smokeDepth: (origin: any, direction: any, distance: any) => number;
            rayBlocked: (origin: any, direction: any, distance: any) => boolean;
            blast: (position: any, radiusM: any, damage: any) => void;
            isBurning: (id: any) => boolean;
            readonly burningCount: number;
        } | null;
        igniteCell(face: any, I: any, J: any, source?: number): any;
        ignite(position: any, source?: number): any;
        igniteArea(position: any, radiusM: any, source?: number): any;
        extinguishCell(face: any, I: any, J: any, radiusCells?: number): any;
        extinguish(position: any, radiusMetres?: number): any;
        explode(position: any, { radiusM, igniteRadiusM, damage, source }?: {
            damage?: number | undefined;
            igniteRadiusM?: number | undefined;
            radiusM?: number | undefined;
            source?: number | undefined;
        }): any;
        incendiaryHit({ radiusM }?: {
            radiusM?: number | undefined;
        }): (ctx: any, hit: any) => void;
        setWind(vector: any): any;
        setMoisture(value: any): any;
        setRain(value: any): any;
        stateAt(position: any): any;
        stateAtLocal(x: any, z: any): any;
        isTrunkCharred(trunkId: any): boolean;
        stageMap(options: any): {
            data: Uint8Array<ArrayBuffer>;
            width: number;
            height: number;
            slotCapacity: number;
            acquire: (face: any, ti: any, tj: any) => any;
            release: (face: any, ti: any, tj: any) => boolean;
            slotValueOfCell: (face: any, I: any, J: any) => number;
            slotValueOfTrunk: (trunkId: any) => number;
            texelOf: (value: any, out: any) => any;
            sync: () => number;
            stats: {
                syncs: number;
                tilesWritten: number;
                bytesWritten: number;
                resolves: number;
            };
            dirtySlots: Int32Array<ArrayBuffer>;
            blockOrigin: (slot: any) => {
                x: number;
                y: number;
            };
            readonly watchedTiles: number;
        };
        isBurning(id: any): boolean;
        smokeDepth(origin: any, direction: any, distance: any): number;
        rayBlocked(origin: any, direction: any, distance: any): boolean;
        applyRemote(payload: any): {
            ok: boolean;
            rejected: number;
            reason: any;
            rewound: number;
            checksum: {
                tick: any;
                hash: any;
            } | null;
            adopted: {
                tick: number;
                hash: any;
                bytes: number;
            } | null;
        };
        checksum(): any;
        keyframeMessage(): {
            type: string;
            k: any[];
        };
        requestResync(): {
            type: string;
            r: any[];
        };
        rewindTo(tick: any): any;
        tick(dt: any): void;
        destroy(): void;
    };
    defineSteering(spec: any): {
        step(from: any, target: any, dt: any, peers: any): {
            position: any[];
            velocity: number[];
            arrived: boolean;
        };
        followPath(from: any, waypoints: any, dt: any, state: any, peers: any): {
            position: any[];
            velocity: number[];
            done: boolean;
            state: any;
        };
    };
    defineCheckpoint(spec: any): any;
    definePickup(spec: any): {
        readonly collected: boolean;
        reset(): void;
        tick(dt: any): void;
    };
    defineDestructible(spec: any): any;
    defineSoftbody(spec: any): {
        readonly ready: boolean;
        readonly particleCount: number;
        readonly pinnedKeys: Set<any>;
        tick: (dt: any) => void;
        positions: () => Float64Array<ArrayBuffer>;
        publish: () => boolean;
        setPin: (col: any, row: any, pinned: any) => boolean;
        dispose: () => void;
        onChartReanchor({ transfer }: {
            transfer: any;
        }): void;
    };
    defineFluid(spec: any): {
        readonly ready: boolean;
        readonly particleCount: number;
        tick: (dt: any) => void;
        positions: () => Float64Array<ArrayBuffer>;
        publish: () => boolean;
        dispose: () => void;
        onChartReanchor({ transfer }: {
            transfer: any;
        }): void;
    };
    defineFluid3D(spec: any): {
        readonly ready: boolean;
        readonly particleCount: number;
        tick: (dt: any) => void;
        positions: () => Float64Array<ArrayBuffer>;
        publish: () => boolean;
        dispose: () => void;
    };
    defineBuoyancy(spec: any): {
        readonly submersionFrac: number;
        readonly submerged: boolean;
        tick(dt: any): void;
    };
    defineTeams(spec: any): {
        assignPlayer(playerId: any, team: any): string | null;
        removePlayer(playerId: any): boolean;
        getTeam(playerId: any): any;
        getMembers(team: any): any[];
        addScore(team: any, delta?: number): number | undefined;
        setScore(team: any, n: any): number | undefined;
        getScore(team: any): number;
        getScores(): {
            id: any;
            label: any;
            color: any;
            score: number;
            members: any[];
        }[];
        getTeams(): any[];
        smallestTeam(): any;
        leader(): any;
        reset(): void;
        broadcast(): void;
    };
    defineWeapon(spec: any): {
        readonly ammo: any;
        readonly magazine: any;
        readonly reloading: boolean;
        canFire(): boolean;
        fire(shooterId: any, origin: any, dir: any, opts?: {}): {
            fired: boolean;
            reason: string;
        } | {
            fired: boolean;
            hit: boolean;
            targetPlayerId: null;
            killed: boolean;
            ammo: any;
        };
        reload(shooterId: any): boolean;
        setAmmo(n: any): any;
    };
    definePlayerInventory(spec: any): {
        add(pid: any, item: any, n?: number): any;
        remove(pid: any, item: any, n?: number): number;
        count(pid: any, item: any): any;
        has(pid: any, item: any, n?: number): boolean;
        items(pid: any): {
            [k: string]: any;
        };
        currency(pid: any): any;
        earn(pid: any, amount: any): any;
        canAfford(pid: any, amount: any): boolean;
        spend(pid: any, amount: any): boolean;
        buy(pid: any, item: any): {
            ok: boolean;
            reason: string;
            currency?: undefined;
            granted?: undefined;
        } | {
            reason?: undefined;
            ok: boolean;
            currency: any;
            granted: {};
        };
        dropOnDeath(pid: any): {
            dropped: {};
            kept: {};
        };
        reset(pid: any): void;
        clearAll(): void;
        push(pid: any): void;
    };
    definePath(points: any): any;
    navmesh(worldName?: any): any;
    _chartLocalNavmesh(navmesh: any): any;
    raycast(origin: any, direction: any, maxDistance?: number, excludeBodyId?: null): any;
    canSee(fromPos: any, toPos: any, opts?: {}): boolean;
    get terrainBodyId(): any;
    terrainHeightAt(x: any, z: any): any;
    terrainKindAt(x: any, z: any): any;
    navCostAt(x: any, z: any): 0.5 | 1 | 2 | 3 | 8;
    seaLevelAt(x: any, z: any): number | null;
    get seaLevel(): number | null;
    get terrain(): {
        startStreaming: (tcfg: any) => Promise<{
            start: (fallbackCenter?: number[]) => Promise<void>;
            stop: () => void;
            prepareFields: ({ players, heightFn: preparedHeightFn, isAborted }: {
                heightFn: any;
                isAborted?: (() => boolean) | undefined;
                players: any;
            }) => Promise<{
                fields: {
                    cornerX: number;
                    cornerZ: number;
                    center: number[];
                    N: number;
                    samples: Float32Array<ArrayBuffer>;
                    sampleMs: number;
                }[];
                primaryIndex: number;
            } | null>;
            installPrepared: (prepared: any) => {
                installed: number;
                removed: number;
            };
            preparedSurfaceY: (set: any, x: any, z: any) => any;
            setLattice: (next: any) => void;
            placeAllFields: () => void;
            cover: (points: any) => Promise<any>;
            readonly lattice: any;
            readonly liveHeightFn: any;
            readonly coverRadius: number;
            readonly staleEpochDiscards: number;
            resculpt: () => Promise<any>;
            readonly fields: {
                bodyId: any;
                center: any[];
            }[];
            readonly center: any[] | null;
            readonly bodyId: any;
            readonly rebuildCount: number;
            readonly busy: boolean;
            readonly maxFields: any;
        } | null>;
    };
}
