/**
 * NPCProtocol.js — Freddie-to-spoint NPC control protocol.
 *
 * PRD row: ugc-freddie-ai-npc-dialogue
 * FIRST SLICE: define the freddie-to-spoint NPC control protocol (extends FreddieBridge.js
 * viz commands with dialogue state).
 *
 * BLOCKED on: no-npc-entity-class-exists (no PRD row exists yet for an NPC entity class).
 * This slice defines the PROTOCOL — the wire format and semantic contract — so the
 * NPC entity class and the freddie integration can be built in parallel once the
 * entity class lands.
 *
 * The protocol extends the existing FreddieBridge.js (client/core/FreddieBridge.js)
 * which already routes freddie agent commands to in-game actions (viz commands like
 * camera, highlight, spawn markers). This protocol adds the NPC-specific dialogue
 * and goal-management surface.
 *
 * Protocol shape (bidirectional):
 *
 * FROM FREDDIE (agent → spoint):
 *   {
 *     type: 'npc',              // discriminator from existing viz commands
 *     action: string,           // one of the actions below
 *     npcId: string,            // which NPC entity
 *     payload: {...}            // action-specific
 *   }
 *
 * Actions:
 *
 *   npc.say        — NPC speaks dialogue (text + optional audio URI from TTS)
 *     payload: { text: string, audioUri?: string, duration?: number }
 *
 *   npc.think       — NPC shows a "thinking" indicator (LLM is generating)
 *     payload: { thinking: boolean }
 *
 *   npc.emote       — NPC plays an animation/gesture
 *     payload: { animation: string, loop?: boolean, blendMs?: number }
 *
 *   npc.goal         — NPC sets a goal (move to, interact with, etc.)
 *     payload: { kind: 'move'|'interact'|'follow'|'flee', target: string|{x,y,z},
 *                priority: number, timeoutMs?: number }
 *
 *   npc.goal.clear   — NPC clears a goal
 *     payload: { goalId: string }
 *
 *   npc.spawn        — (future) spawn a new NPC entity
 *     payload: { template: string, position: {x,y,z}, name: string, personality: object }
 *
 *   npc.despawn      — remove an NPC entity
 *     payload: { reason: string }
 *
 * FROM SPOINT (game → freddie):
 *   {
 *     type: 'npc-event',
 *     npcId: string,
 *     event: string,           // one of the events below
 *     payload: {...}
 *   }
 *
 * Events:
 *
 *   npc.seen        — NPC entered a player's view/proximity
 *     payload: { playerId: string, distance: number, fov: boolean }
 *
 *   npc.interacted   — player pressed E near this NPC
 *     payload: { playerId: string, playerName: string }
 *
 *   npc.goal.complete — NPC reached/finished a goal
 *     payload: { goalId: string, kind: string, result: 'success'|'fail'|'timeout' }
 *
 *   npc.goal.failed   — NPC failed a goal
 *     payload: { goalId: string, kind: string, reason: string }
 *
 *   npc.damaged      — NPC took damage
 *     payload: { sourceId: string, amount: number, kind: string }
 *
 *   npc.worldstate   — periodic world-state update for the NPC's awareness
 *     payload: { nearbyPlayers: string[], nearbyEntities: string[], timeOfDay: number,
 *                weather: string, dangerLevel: number }
 *
 * Proximity voice:
 *  - When an NPC says something, the audio is spatialized using the existing
 *    WebAudio position-based panning (client already has positional audio for
 *    player footsteps/weapons).
 *  - TTS is generated by neutts_synth (freddie's existing TTS plugin) and
 *    delivered as an audioUri pointing to a generated .wav/.mp3.
 *  - The client caches TTS audio by (text, voice) hash to avoid re-downloading
 *    repeated lines.
 *
 * Utility AI / LLM split:
 *  - Combat decisions (target selection, movement, ability use) are handled by
 *    a lightweight utility AI running in spoint's own tick loop (deterministic,
 *    low-latency, no LLM round-trip).
 *  - Dialogue/quest decisions are handled by the LLM (freddie), which has
 *    higher latency but much richer context — the LLM receives the npc.worldstate
 *    event and responds with npc.say/npc.goal commands.
 *  - The split is clean: the utility AI owns the per-tick combat loop, the LLM
 *    owns the conversation/quest loop, and they share the same goal queue on the
 *    NPC entity (LLM adds goals, utility AI executes them, npc.goal.complete
 *    feeds back to the LLM).
 */

/**
 * Validate an inbound NPC command from freddie.
 * @param {object} cmd
 * @returns {{ valid: boolean, error?: string }}
 */
export function validateNPCCommand(cmd) {
  if (!cmd || cmd.type !== 'npc') return { valid: false, error: 'expected type: "npc"' }
  if (typeof cmd.action !== 'string') return { valid: false, error: 'action is required' }
  if (typeof cmd.npcId !== 'string') return { valid: false, error: 'npcId is required' }
  return { valid: true }
}

/**
 * Build an NPC event to send to freddie.
 * @param {string} npcId
 * @param {string} event
 * @param {object} payload
 * @returns {{ type: 'npc-event', npcId: string, event: string, payload: object }}
 */
export function buildNPCEvent(npcId, event, payload = {}) {
  return { type: 'npc-event', npcId, event, payload }
}

/** Supported NPC command actions */
export const NPC_ACTIONS = [
  'npc.say',
  'npc.think',
  'npc.emote',
  'npc.goal',
  'npc.goal.clear',
  'npc.spawn',
  'npc.despawn',
]

/** Supported NPC event types */
export const NPC_EVENTS = [
  'npc.seen',
  'npc.interacted',
  'npc.goal.complete',
  'npc.goal.failed',
  'npc.damaged',
  'npc.worldstate',
]