// GENERATED by scripts/gen-height.mjs from src/shaders/terrain.glsl -- DO NOT EDIT.
// The GLSL is the single source of truth; re-run `node scripts/gen-height.mjs` after editing
// the terrain HEIGHT functions. `g` = the GLSL runtime shim (glsl-rt.js); `U` = uniform values;
// hpfSample is supplied by the caller (the pure-JS anchor-field) via the U/ctx closure.
// GPU-texture-only calls reachable from a transpiled height fn (sculptOverrideAt etc, see
// STUB_FNS in gen-height.mjs) are emitted below as fixed-value stubs, not transpiled.
import * as g from './glsl-rt.js';

export function makeHeight(U, hpfSample) {
  const C_LTYPE_FBM = 0;
  const C_LTYPE_RIDGED = 1;
  const C_noiseLayer0 = { ltype: C_LTYPE_RIDGED, numOct: 10, gain: 0.5, ridgeOffset: 1.064, ridgeExp: 1.005, warpStr: 1.6, hmin: 0.0, hmax: 1.0 };
  const C_noiseLayer1 = { ltype: C_LTYPE_FBM, numOct: 18, gain: 0.5, ridgeOffset: 1.064, ridgeExp: 1.665, warpStr: 2.6, hmin: -2.0, hmax: 2.0 };
  const C_noiseLayer2 = { ltype: C_LTYPE_RIDGED, numOct: 18, gain: 0.5, ridgeOffset: 1.064, ridgeExp: 1.1, warpStr: 0.9, hmin: -2.0, hmax: 2.0 };
  function sculptOverrideAt(dir0) { return 0.0; }
  function h3(p) {
    p = g.fract(g.mul(p, g.vec3(0.1031, 0.1030, 0.0973)));
    p = g.add(p, g.dot(p, g.add(g.sw(p, 'yxz'), 33.33)));
    return ((g.fract(((g.sw(p, 'x') + g.sw(p, 'y')) * g.sw(p, 'z'))) * 2.0) - 1.0);
  }

  function snoise3(P) {
    let fl = g.floor(P);
    let i = g.ivec3(fl);
    let f = g.sub(P, fl);
    let u = g.mul(g.mul(g.mul(f, f), f), g.add(g.mul(f, g.sub(g.mul(f, 6.0), 15.0)), 10.0));
    let i0 = g.vec3(i);
    let i1 = g.add(g.vec3(i), g.vec3(1.0));
    let n000 = h3(i0);
    let n100 = h3(g.vec3(g.sw(i1, 'x'), g.sw(i0, 'y'), g.sw(i0, 'z')));
    let n010 = h3(g.vec3(g.sw(i0, 'x'), g.sw(i1, 'y'), g.sw(i0, 'z')));
    let n110 = h3(g.vec3(g.sw(i1, 'x'), g.sw(i1, 'y'), g.sw(i0, 'z')));
    let n001 = h3(g.vec3(g.sw(i0, 'x'), g.sw(i0, 'y'), g.sw(i1, 'z')));
    let n101 = h3(g.vec3(g.sw(i1, 'x'), g.sw(i0, 'y'), g.sw(i1, 'z')));
    let n011 = h3(g.vec3(g.sw(i0, 'x'), g.sw(i1, 'y'), g.sw(i1, 'z')));
    let n111 = h3(i1);
    let x00 = g.mix(n000, n100, g.sw(u, 'x'));
    let x10 = g.mix(n010, n110, g.sw(u, 'x'));
    let x01 = g.mix(n001, n101, g.sw(u, 'x'));
    let x11 = g.mix(n011, n111, g.sw(u, 'x'));
    return g.mix(g.mix(x00, x10, g.sw(u, 'y')), g.mix(x01, x11, g.sw(u, 'y')), g.sw(u, 'z'));
  }

  function value_fbm(x, gain, numOctaves) {
    let v = 0.0;
    let a = 1.0;
    let norm = 0.0;
    let p = x;
    let nb = (numOctaves + ((U.uNoUnroll > 0) ? (U.uNoUnroll - 64) : 0));
    for (let i = 0; (i < nb); i++) {
      v += (a * snoise3(p));
      norm += a;
      a *= gain;
      p = g.mul(p, 2.0);
    }
    return (v / norm);
  }

  function value_fbm_scaled(x, gain, numOctaves, lo, hi) {
    return (lo + ((hi - lo) * ((value_fbm(x, gain, numOctaves) * 0.5) + 0.5)));
  }

  function rotate_domain(pos, angle) {
    let c = g.cos(angle);
    let s = g.sin(angle);
    return g.vec3(((c * g.sw(pos, 'x')) - (s * g.sw(pos, 'z'))), g.sw(pos, 'y'), ((s * g.sw(pos, 'x')) + (c * g.sw(pos, 'z'))));
  }

  function value_ridged_fbm_rot(x_in, gain, numOctaves, offset, exponent) {
    let v = 0.0;
    let w = 1.0;
    let norm = 0.0;
    let a = 1.0;
    let p = x_in;
    let nb = (numOctaves + ((U.uNoUnroll > 0) ? (U.uNoUnroll - 64) : 0));
    for (let i = 0; (i < nb); i++) {
      let signal = (offset - g.abs(snoise3(p)));
      signal = g.pow(g.max(signal, 0.0), exponent);
      v += ((signal * w) * a);
      norm += a;
      w = g.clamp(signal, 0.0, 1.0);
      a *= gain;
      p = rotate_domain(g.mul(p, 2.0), (g.float(i) * 0.5236));
    }
    return (v / g.max(norm, 1e-5));
  }

  function value_ridged_fbm_rot_scaled(x, gain, numOctaves, offset, exponent, lo, hi) {
    return (lo + ((hi - lo) * ((value_ridged_fbm_rot(x, gain, numOctaves, offset, exponent) * 0.5) + 0.5)));
  }

  function eval_layer(pos, L) {
    let raw = 0;
    let t = 0;
    if ((L.ltype == C_LTYPE_FBM)) {
      raw = value_fbm(pos, L.gain, L.numOct);
      t = ((raw * 0.5) + 0.5);
    }
    else {
      raw = value_ridged_fbm_rot(pos, L.gain, L.numOct, L.ridgeOffset, L.ridgeExp);
      t = raw;
    }
    return (L.hmin + ((L.hmax - L.hmin) * t));
  }

  function sample_fractal_terrain(pCoords) {
    let h0 = eval_layer(pCoords, C_noiseLayer0);
    let warpOff = g.mul(g.mul(pCoords, C_noiseLayer0.warpStr), h0);
    let warped = g.add(pCoords, warpOff);
    let h1 = eval_layer(warped, C_noiseLayer1);
    let h2 = eval_layer(warped, C_noiseLayer2);
    return (((h0 + h1) + h2) / 3.0);
  }

  function fractalTerrainH(dir0) {
    let dirN = g.normalize(dir0);
    let p = g.mul(dirN, 3.0);
    let raw = sample_fractal_terrain(p);
    let h = ((raw - 0.17) * 0.6);
    let pmix = ((snoise3(g.add(g.mul(p, 0.53), g.vec3(123.0, 456.0, 789.0))) * 0.5) + 0.5);
    let vPower = g.mix(0.95, 1.3, pmix);
    if ((h > 0.0)) {
      h = g.pow(h, (0.8 * vPower));
    }
    else {
      h = (-g.pow((-h), (0.8 * vPower)));
    }
    let cRatio = g.clamp(((snoise3(g.mul(dirN, 4.0)) * 0.5) + 0.7), 0.3, 1.0);
    h *= cRatio;
    return h;
  }

  function vhash(p) {
    let q = g.uvec2(g.ivec2(p));
    let h = ((g.sw(q, 'x') * 1597334677) + (g.sw(q, 'y') * 3812015801));
    h ^= g.ushr(h, 16);
    h *= 2654435769;
    h ^= g.ushr(h, 15);
    h *= 2246822519;
    h ^= g.ushr(h, 13);
    return (g.float(h) * (1.0 / 4294967296.0));
  }

  function vnoise2(p) {
    let i = g.floor(p);
    let f = g.sub(p, i);
    let u = g.mul(g.mul(g.mul(f, f), f), g.add(g.mul(f, g.sub(g.mul(f, 6.0), 15.0)), 10.0));
    let a = vhash(i);
    let b = vhash(g.add(i, g.vec2(1, 0)));
    let c = vhash(g.add(i, g.vec2(0, 1)));
    let d = vhash(g.add(i, g.vec2(1, 1)));
    return ((g.mix(g.mix(a, b, g.sw(u, 'x')), g.mix(c, d, g.sw(u, 'x')), g.sw(u, 'y')) * 2.0) - 1.0);
  }

  function faceWarp(p) {
    return g.mul(U.defRadius, g.tan(g.mul(g.div(p, U.defRadius), 0.7853981634)));
  }

  function composeHeight(dir0, faceLocal, tileM) {
    let frac = fractalTerrainH(dir0);
    let h = ((frac * 750000.0) + U.uLandBias);
    if ((h < 0.0)) {
      h = g.max((h * 1.25), (-350000.0));
    }
    else {
      let bShelf = ((U.uBeachShelfM > 1.0) ? U.uBeachShelfM : 150.0);
      if ((h < bShelf)) {
        h = (((h * h) / bShelf) * (2.0 - (h / bShelf)));
      }
    }
    h = (h * ((U.uReliefScale > 0.0) ? U.uReliefScale : 1.0));
    h += sculptOverrideAt(dir0);
    return h;
  }

  function continentalBias(dir) {
    return g.sw(hpfSample(dir), 'r');
  }

  return { snoise3, composeHeight, continentalBias };
}
