export default {
  presets: ['tps'],
  port: 3001,
  physicsBodyBudget: 256,
  scene: {
    skyColor: 0x87ceeb,
    fogColor: 0x87ceeb,
    fogNear: 500,
    fogFar: 2000,
    ambientColor: 0xfff4d6,
    ambientIntensity: 0.5,
    sunColor: 0xffffff,
    sunIntensity: 1.5,
    sunPosition: [21, 50, 20],
    fillColor: 0x4488ff,
    fillIntensity: 0.3,
    fillPosition: [-20, 30, -10],
    shadowMapSize: 1024,
    shadowBias: 0.0038,
    shadowNormalBias: 0.6
  },
  trustedApps: [],
  placeableApps: ['checkpoint-marker', 'trigger-volume', 'button', 'spawn-point', 'respawn-zone'],
  terrain: { enabled: false },
  entities: [
    { id: 'tutorial-app', position: [0, 0, 0], app: 'tutorial' },
    { id: 'tut-step-wasd',     position: [0, 1, 3], app: 'checkpoint-marker', config: { order: 0, radius: 3, color: '#33ccff' } },
    { id: 'tut-step-sprint',   position: [0, 1, 9], app: 'checkpoint-marker', config: { order: 1, radius: 3, color: '#33ccff' } },
    { id: 'tut-step-jump',     position: [0, 1, 15], app: 'checkpoint-marker', config: { order: 2, radius: 3, color: '#33ccff' } },
    { id: 'tut-button', position: [0, 1, 21], app: 'button', config: { target: 'tutorial-app', channel: 'tutorial.finish', prompt: 'Press E to interact' } },
    { id: 'tut-respawn', position: [0, 0.5, 0], app: 'respawn-zone', config: { radius: 5 } },
  ],
  spawnPoint: [0, 1.5, 0],
}